# Pull base image.
FROM openjdk:8-jre-alpine

# Install H2
RUN \
  cd /tmp && \
  wget http://www.h2database.com/h2-2019-03-13.zip && \
  unzip h2-2019-03-13.zip && \
  rm -f h2-2019-03-13.zip && \
  mkdir -p /opt/h2 && \
  mv /tmp/h2 /opt && \
  mkdir -p /opt/h2-data

# Expose ports.
#   - 9092: H2 Server
#   -   8082: H2 Console
EXPOSE 8082 9092


VOLUME /h2-data

# Define default command
CMD java -cp /opt/h2/bin/h2*.jar org.h2.tools.Server -web -webAllowOthers -tcp -tcpAllowOthers  -ifNotExists -baseDir /opt/h2-data