# Start with a base image containing Java runtime
FROM openjdk:8-jdk-alpine

# Add Maintainer Info
LABEL maintainer="Rakesh Singh Rana"

# Make port 8080 available to the world outside this container
EXPOSE 8080

# The application's jar file
ARG JAR_FILE=target/spring-boot-kubernetes-1.0.0.jar

# Add the application's jar to the container
ADD ${JAR_FILE} spring-boot-kubernetes-1.0.0.jar

# Run the jar file
ENTRYPOINT ["java","-jar","/spring-boot-kubernetes-1.0.0.jar"]